/**
 * This file contains all the query / mutation keys
 */

export const QueryKeys = {
  login: 'login',
  dashboardAnalytics: 'dashboard-analytics-data',
  userDetails: 'user-details',
  allUsers: 'all-users',
  filterUsers: 'filter-users',
  updateUserRole: 'update-user-role',
  addUser: 'add-user',
  userDetailsById: 'user-details-by-id',
  updateUserDetails: 'update-user-details',
  deleteUser: 'delete-user',
  uploadImage: 'upload-image',
  fetchMovies: 'fetch-movies',
  filterMovies: 'filter-movies',
  movieDetails: 'movie-details',
  deleteMovie: 'delete-movie',
  bulkDeleteMovies: 'bulk-delete-movies',
  addMovie: 'add-movie',
  updateMovie: 'update-movie',
  bulkAddMovies: 'bulk-add-movies',
  fetchAllGames: 'fetch-all-games',
  filterGames: 'filter-games',
  gameDetailsById: 'game-details-by-id',
  addGame: 'add-game',
  deleteGame: 'delete-game',
  bulkDeleteGames: 'bulk-delete-games',
  updateGame: 'update-game',
  bulkAddGames: 'bulk-add-games',
  fetchAllTvShows: 'fetch-all-tv-shows',
  fetchTvShowByFilter: 'fetch-tv-show-by-filter',
  fetchTvShowById: 'fetch-tv-show-by-id',
  fetchSeasonById: 'fetch-season-by-id',
  fetchEpisodeById: 'fetch-episode-by-id',
  addEpisode: 'add-episode',
  deleteEpisode: 'delete-episode',
  editEpisode: 'edit-episode',
};
